### ISSUE TITLE
Units of measurements

### ISSUE THREAD

**Issue by cmolitor** [areinhardt/tracebase#3]
Hello.

I am interested in the data but I couldn't find any information describing the columns in the data file. The first six columns are time but the seventh and eighth? Power in W? Why two values?

Thanks for the clarification.

Best regards
Christoph

**Comment by areinhardt** [comment]
There's only three columns in each Tracebase file, separated by semicolons. Their description is available in the "Trace format" section of the [README](https://github.com/areinhardt/tracebase/blob/master/README.md) file: "Each entry in the file contains the date and time of its collection and the power consumption readings averaged over time durations of one and eight seconds, respectively."

The third column (8-second average) was provided by the smart plugs we used to collect the data set. If you're planning to work on averaged data anyway, it's slightly more accurate because the value is rounded only once, as compared to eight times the rounding error when using eight consecutive values from the second column.

**Comment by cmolitor** [comment]
Thank you. No idea, why I didn't see it in the first place.
